### ISSUE TITLE
Problem with the schema

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/ostranslator-ii#2]
When I ran the task I got an error telling me to use lower case letters and underscores. My schema name met these criteria and it created it anyway.

**Comment by mostlyAtNight** [comment]
There is an issue where the import would proceed even if the schema name was not consisting of only lower-case and underscored.  This is due to be resolved in a moment.  

If the schema name you used contained only lower-case and the underscore ( _ ) character then please let me know and I will re-open the ticket.
